#NAME: Ethan Ngo
#EMAIL: ethan.ngo2019@gmail.com
#ID: 205416130

default:
	gcc -Wall -Wextra -g -o lab1a lab1a.c

clean:
	rm -f lab1a *.tar.gz

dist:
	tar -czvf lab1a-205416130.tar.gz lab1a.c Makefile README