#NAME: Ethan Ngo
#EMAIL: ethan.ngo2019@gmail.com
#ID: 205416130

default:
	gcc -Wall -Wextra -g -o lab0 lab0.c

check:
	./smoketest.sh

clean:
	rm -f lab0 *.txt *.tar.gz

dist:
	tar -czvf lab0-205416130.tar.gz lab0.c Makefile README backtrace.png breakpoint.png smoketest.sh